### ISSUE TITLE
Group permission placeholder

### ISSUE THREAD

**Issue by LogGits** [LuckPerms/placeholders#17]
e.g.
`%luckperms_{groupname}_has_permission_{permission}%`

which returns true/false.

I want to return this value to a deluxemenu gui item to show if a group has access to chat (for an admin chat toggle system) so i can write 
```
"Enabled: %luckperms_{groupname}_has_permission_{permission}%"
```

**Comment by lucko** [comment]
Sorry, I feel like this is a bit too niche for including in the LP expansion.

Of course, you (or another developer) can access this info using the API and implement your own placeholder for it :)
