### ISSUE TITLE
Incorrect Time Parsing For Expiry Time Placeholders

### ISSUE THREAD

**Issue by delbertina** [LuckPerms/placeholders#19]
I use a menu system to display expiry time of specific permissions to players and have noticed that recently the time remaining displayed is being funky. The permissions expire at the correct time, but just the value that the placeholder displays is incorrect in many cases. 

I have a system setup to add 72h to the temp permission time so here's what it displays for approx 3, 6, and 9 days. 
![image](https://user-images.githubusercontent.com/6349928/91648319-a884f300-ea2b-11ea-8bdc-97134eedf0d3.png)

Running LuckPerms 5.1.93 (also tried latest 5.1.96) , and PAPI 2.10.9 w/ luckperms expansion version 5.0-R2
Paper 1.16.1 build # 136

An example of the command that is run to add the time
`lp group basic permission settemp mcmmo.perks.xp.double true 72h`
An example of the placeholder used to display the time
`%luckperms_inherited_expiry_time_mcmmo.perks.xp.double%`

I'm almost 99% sure this was working as expected ~July 4th so a change to either Luckperms, PAPI or the expansion within the last 2 months should be the culprit. This makes me think it was the 5.1.93 release for Luckperms that caused this issue, but it is manifesting itself in the placeholders so thought it best to report here.

Possibly unrelated, but it also bugs out somewhere between 24 days and 27 days. 24 days displays as 23 days and change where as 27 days displays as 2 days and change. The console output looks correct and I assume the permission will expire on time, but just the placeholder bugs out. 

: )

Edit:
Tried updating to 5.2.14 and the bug is still present.

**Comment by andris155** [comment]
Same problem with temp groups.

**Comment by DrakMC** [comment]
I have the same problem. Please fix it as soon as possible.

**Comment by lucko** [comment]
This is a PlaceholderAPI bug, but I have fixed it in the LP placeholders anyway..: 6b832815284dafc79c1b628fac809851331f9827
