### ISSUE TITLE
Project doesn't get published

### ISSUE THREAD

**Issue by lusu007** [LuckPerms/placeholders#27]
I noticed that this project unfortunately doesn't get published to https://oss.sontaype.org. 
Is this on purpose?

Because this makes contributing to e.g. gChat pretty annoying. Maven can't resolve the placeholders-common dependency.

**Comment by underscore11code** [comment]
This project isn't intended to be API. If you want to interact with LP programmatically, you should be using the [Developer API](https://luckperms.net/wiki/Developer-API).

**Comment by lusu007** [comment]
But the problem is that it gets used in gChat. It is not possible to compile gChat at the moment.

**Comment by emilyy-dev** [comment]
You can build & install this project into your maven local repository

**Comment by underscore11code** [comment]
Oh ok I see. Looks like Luck does have this published to his own repo (`https://repo.lucko.me` for use in maven, https://nexus.lucko.me if you wish to browse). Adding that repo & bumping to `5.1-SNAPSHOT` should fix, but this issue should have been made on the gChat repo.

**Comment by lusu007** [comment]
> You can build & install this project into your maven local repository

Yeah, I know. But it is pretty annoying.


> Oh ok I see. Looks like Luck does have this published to his own repo (`https://repo.lucko.me` for use in maven, [nexus.lucko.me](https://nexus.lucko.me) if you wish to browse). Adding that repo & bumping to `5.1-SNAPSHOT` should fix, but this issue should have been made on the gChat repo.

Oh, nice thanks. I didn't know that a private repository exists. Thank you!

**Comment by skerit** [comment]
What's the URL you'd have to use as repository?
Using `https://repo.lucko.me/repository/maven-jenkins/` does not seem to work.

**Comment by powercasgamer** [comment]
> What's the URL you'd have to use as repository? Using `https://repo.lucko.me/repository/maven-jenkins/` does not seem to work.

Just `https://repo.lucko.me/`
