### ISSUE TITLE
Fabric 1.19 crashing

### ISSUE THREAD

**Issue by u0398** [LuckPerms/placeholders#35]
I've been trying to get LuckPerms placeholders to work without success. I'm new to fabric, so I may be making some boneheaded mistakes. Here's the crash report:

[crash-2022-07-02_22.30.23-server.txt](https://github.com/LuckPerms/placeholders/files/9034132/crash-2022-07-02_22.30.23-server.txt)

I have tried multiple versions of Fabric, and Patbox/TextPlaceholderAP. I get the same error regardless.

**Comment by nikijaz** [comment]
#34

**Comment by u0398** [comment]
The most recent ``5.4-SNAPSHOT`` does not crash, but I've been unable to get LuckPerms place holders to work. 

It's possible I am doing something wrong though. I am assuming the fabric jar should be placed in the ``mods/`` folder.

**Comment by u0398** [comment]
With the the latest ``Patbox/TextPlaceholderAPI`` and ``LuckPerms
/
placeholders`` the mod seems to be working.

I do need to reload Styled Chat and Styled Player List after every server reboot, but that may be an issue with those mods.
