### ISSUE TITLE
Identifier constructor is private

### ISSUE THREAD

**Issue by Siebrenvde** [LuckPerms/placeholders#57]
Since 1.21 the constructors for `net.minecraft.util.Identifier` have been privatised. [(javadoc) ](https://maven.fabricmc.net/docs/yarn-1.21+build.2/net/minecraft/util/Identifier.html#%3Cinit%3E(java.lang.String,java.lang.String))
It should be replaced with `Identifier.of()`. [(javadoc)](https://maven.fabricmc.net/docs/yarn-1.21+build.1/net/minecraft/util/Identifier.html#of(java.lang.String,java.lang.String))

**Comment by N1zard** [comment]
please, fix
